/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Search;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;

/**
 *
 * @author alulab14
 */
public class BusquedaAvanzada extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaAvanzada
     */
    public BusquedaAvanzada() {
        initComponents();
        Font font = lblLinkIniciarSesion.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lblLinkIniciarSesion.setFont(font.deriveFont(attributes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxTema1 = new javax.swing.JCheckBox();
        jCheckBoxTema2 = new javax.swing.JCheckBox();
        jCheckBoxTema3 = new javax.swing.JCheckBox();
        jCheckBoxTema4 = new javax.swing.JCheckBox();
        jCheckBoxTema5 = new javax.swing.JCheckBox();
        jCheckBoxTema6 = new javax.swing.JCheckBox();
        jCheckBoxTema7 = new javax.swing.JCheckBox();
        jCheckBoxTema8 = new javax.swing.JCheckBox();
        jCheckBoxTema9 = new javax.swing.JCheckBox();
        jCheckBoxTema10 = new javax.swing.JCheckBox();
        jCheckBoxTema11 = new javax.swing.JCheckBox();
        jCheckBoxTema12 = new javax.swing.JCheckBox();
        jCheckBoxTema13 = new javax.swing.JCheckBox();
        jCheckBoxTema14 = new javax.swing.JCheckBox();
        jCheckBoxTema15 = new javax.swing.JCheckBox();
        jCheckBoxTema16 = new javax.swing.JCheckBox();
        jCheckBoxTema17 = new javax.swing.JCheckBox();
        jCheckBoxTema18 = new javax.swing.JCheckBox();
        jCheckBoxTema19 = new javax.swing.JCheckBox();
        jCheckBoxTema20 = new javax.swing.JCheckBox();
        jCheckBoxTema21 = new javax.swing.JCheckBox();
        jCheckBoxTema22 = new javax.swing.JCheckBox();
        jCheckBoxTema23 = new javax.swing.JCheckBox();
        jCheckBoxTema24 = new javax.swing.JCheckBox();
        bttnBuscar = new javax.swing.JButton();
        lblLinkIniciarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Busqueda Avanzada");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Título :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText(" Autor :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tipo :");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Temas Relacionados :");

        jCheckBoxTema1.setText("Tema1");

        jCheckBoxTema2.setText("Tema 2");

        jCheckBoxTema3.setText("Tema 3");

        jCheckBoxTema4.setText("Tema 4");

        jCheckBoxTema5.setText("Tema 5");

        jCheckBoxTema6.setText("Tema 10");

        jCheckBoxTema7.setText("Tema 5");

        jCheckBoxTema8.setText("Tema 6");

        jCheckBoxTema9.setText("Tema 7");

        jCheckBoxTema10.setText("Tema 8");

        jCheckBoxTema11.setText("Tema 9");

        jCheckBoxTema12.setText("Tema 11");

        jCheckBoxTema13.setText("Tema 12");

        jCheckBoxTema14.setText("Tema 22");

        jCheckBoxTema15.setText("Tema 13");

        jCheckBoxTema16.setText("Tema 15");

        jCheckBoxTema17.setText("Tema 14");

        jCheckBoxTema18.setText("Tema 16");

        jCheckBoxTema19.setText("Tema 17");

        jCheckBoxTema20.setText("Tema 18");

        jCheckBoxTema21.setText("Tema 19");

        jCheckBoxTema22.setText("Tema 20");

        jCheckBoxTema23.setText("Tema 21");

        jCheckBoxTema24.setText("Tema 24");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTema13)
                    .addComponent(jCheckBoxTema18)
                    .addComponent(jCheckBoxTema22)
                    .addComponent(jCheckBoxTema5)
                    .addComponent(jCheckBoxTema1)
                    .addComponent(jCheckBoxTema10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jCheckBoxTema15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jCheckBoxTema19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jCheckBoxTema23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTema11)
                            .addComponent(jCheckBoxTema7)
                            .addComponent(jCheckBoxTema2))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTema17)
                            .addComponent(jCheckBoxTema20)
                            .addComponent(jCheckBoxTema14))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTema24)
                            .addComponent(jCheckBoxTema21)
                            .addComponent(jCheckBoxTema16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTema6)
                            .addComponent(jCheckBoxTema8)
                            .addComponent(jCheckBoxTema3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTema4)
                            .addComponent(jCheckBoxTema9)
                            .addComponent(jCheckBoxTema12))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTema1)
                    .addComponent(jCheckBoxTema2)
                    .addComponent(jCheckBoxTema4)
                    .addComponent(jCheckBoxTema3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTema5)
                    .addComponent(jCheckBoxTema7)
                    .addComponent(jCheckBoxTema8)
                    .addComponent(jCheckBoxTema9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTema10)
                    .addComponent(jCheckBoxTema11)
                    .addComponent(jCheckBoxTema6)
                    .addComponent(jCheckBoxTema12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTema13)
                    .addComponent(jCheckBoxTema15)
                    .addComponent(jCheckBoxTema17)
                    .addComponent(jCheckBoxTema16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTema18)
                    .addComponent(jCheckBoxTema19)
                    .addComponent(jCheckBoxTema20)
                    .addComponent(jCheckBoxTema21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTema22)
                    .addComponent(jCheckBoxTema23)
                    .addComponent(jCheckBoxTema14)
                    .addComponent(jCheckBoxTema24))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        bttnBuscar.setText("Buscar");

        lblLinkIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        lblLinkIniciarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinkIniciarSesion.setForeground(new java.awt.Color(0, 0, 255));
        lblLinkIniciarSesion.setText("Iniciar Sesión");
        lblLinkIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLinkIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLinkIniciarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(32, 32, 32)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(86, 86, 86))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(535, 535, 535)
                            .addComponent(bttnBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel5)))
                        .addGap(129, 129, 129)
                        .addComponent(lblLinkIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblLinkIniciarSesion)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(bttnBuscar)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void lblLinkIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkIniciarSesionMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_lblLinkIniciarSesionMouseEntered

    private void lblLinkIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkIniciarSesionMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_lblLinkIniciarSesionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaAvanzada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaAvanzada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaAvanzada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaAvanzada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaAvanzada().setVisible(true);
            }
        });
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnBuscar;
    private javax.swing.JCheckBox jCheckBoxTema1;
    private javax.swing.JCheckBox jCheckBoxTema10;
    private javax.swing.JCheckBox jCheckBoxTema11;
    private javax.swing.JCheckBox jCheckBoxTema12;
    private javax.swing.JCheckBox jCheckBoxTema13;
    private javax.swing.JCheckBox jCheckBoxTema14;
    private javax.swing.JCheckBox jCheckBoxTema15;
    private javax.swing.JCheckBox jCheckBoxTema16;
    private javax.swing.JCheckBox jCheckBoxTema17;
    private javax.swing.JCheckBox jCheckBoxTema18;
    private javax.swing.JCheckBox jCheckBoxTema19;
    private javax.swing.JCheckBox jCheckBoxTema2;
    private javax.swing.JCheckBox jCheckBoxTema20;
    private javax.swing.JCheckBox jCheckBoxTema21;
    private javax.swing.JCheckBox jCheckBoxTema22;
    private javax.swing.JCheckBox jCheckBoxTema23;
    private javax.swing.JCheckBox jCheckBoxTema24;
    private javax.swing.JCheckBox jCheckBoxTema3;
    private javax.swing.JCheckBox jCheckBoxTema4;
    private javax.swing.JCheckBox jCheckBoxTema5;
    private javax.swing.JCheckBox jCheckBoxTema6;
    private javax.swing.JCheckBox jCheckBoxTema7;
    private javax.swing.JCheckBox jCheckBoxTema8;
    private javax.swing.JCheckBox jCheckBoxTema9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblLinkIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
