/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Search;

import DataAccess.EjemplarLibroDB;
import DataAccess.Session;
import Modelo.Biblioteca;
import Modelo.EjemplarLibro;
import Modelo.EstadoEjemplar;
import Modelo.Libro;
import Modelo.Piso;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MiguelR
 */
public class InformacionLibro extends javax.swing.JFrame {

    private static final String [] EJEMPLARES_COLUMNS = {"Biblioteca", "Piso", "Id ejemplar", "Estado"};
    private Libro libro;
    private Thread imageLoadingThread;
    
    /**
     * Creates new form InformacionLibro
     * @param libro
     * @param biblioteca
     * @param piso
     */
    public InformacionLibro(Libro libro) {
        this.libro = libro;
        initComponents();

        initValues();
    }
    
    
    
    public void initValues() {
        setTitle(libro.getTitulo());
        lblTitulo.setText(libro.getTitulo());
        
        lblAutores.setText(libro.getAutoresSeparados());
        lblEditorial.setText(libro.getEditorial());
        lblEdicion.setText(libro.getEdicion() + "");
        lblIdioma.setText(libro.getIdioma());
        lblAnhoPub.setText(libro.getAnhoPublicacion() + "");
        lblISBN.setText(libro.getISBN());
        lblNumPag.setText(libro.getNumPaginas() + "");
        
        imageLoadingThread = new Thread(new Runnable() {
            @Override
            public void run() {
                ImageIcon icon = libro.getPortadaGrandeSH(250);
                if(icon!=null) {
                    imgLibro.setIcon(icon);
                    imgLibro.setText("");
                    Dimension newSize = new Dimension(icon.getIconWidth(), icon.getIconHeight());
                    imgLibro.setPreferredSize(newSize);
                    imgLibro.setMaximumSize(newSize);
                    imgLibro.setMinimumSize(newSize);
                    imgLibro.updateUI();
                } else imgLibro.setText("<html><body>sin<br>imagen</body></html>");
                System.out.println(libro.getTitulo());
            }
        });
        imageLoadingThread.start();
        
        ArrayList<EjemplarLibro> ejemplares = libro.getEjemplares();
        String [][] data = new String[ejemplares.size()][4];
        
        int pos = 0;
        for(EjemplarLibro ejemplar: ejemplares) {
            data[pos][0] = ejemplar.getBiblioteca().getNombre();
            data[pos][1] = ejemplar.getPiso().getPiso();
            data[pos][2] = ejemplar.getId() + "";
            data[pos][3] = ejemplar.getEstado().estado;
            pos ++;
        }
        tablaEjemplares.setModel(new DefaultTableModel(data, EJEMPLARES_COLUMNS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        infoAutor = new javax.swing.JLabel();
        infoIdioma = new javax.swing.JLabel();
        infoAnhoPub = new javax.swing.JLabel();
        infoISBN = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEjemplares = new javax.swing.JTable();
        btnPrestar = new javax.swing.JButton();
        imgLibro = new javax.swing.JLabel();
        infoEditorial = new javax.swing.JLabel();
        infoEdicion = new javax.swing.JLabel();
        infoNumPag = new javax.swing.JLabel();
        lblAutores = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        lblAnhoPub = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblNumPag = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        infoAutor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infoAutor.setText("Autores:");

        infoIdioma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infoIdioma.setText("Idioma:");

        infoAnhoPub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infoAnhoPub.setText("Año de Publicacion:");

        infoISBN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infoISBN.setText("ISBN:");

        tablaEjemplares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Biblioteca", "Codigo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEjemplares.setColumnSelectionAllowed(true);
        tablaEjemplares.setGridColor(new java.awt.Color(255, 255, 255));
        tablaEjemplares.setRowSelectionAllowed(false);
        tablaEjemplares.setShowHorizontalLines(false);
        tablaEjemplares.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tablaEjemplares);
        tablaEjemplares.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tablaEjemplares.getAccessibleContext().setAccessibleName("tableEjemplares");

        btnPrestar.setText("Añadir ejemplar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        imgLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLibro.setText("imagen");

        infoEditorial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infoEditorial.setText("Editorial:");

        infoEdicion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infoEdicion.setText("Edicion:");

        infoNumPag.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infoNumPag.setText("Número de páginas:");

        lblAutores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAutores.setText("Autores del libro");

        lblEdicion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEdicion.setText("Edicion del libro");

        lblEditorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEditorial.setText("Editorial del libro");

        lblIdioma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIdioma.setText("Idioma del libro");

        lblAnhoPub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAnhoPub.setText("Año de publicacion");

        lblISBN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblISBN.setText("ISBN");

        lblNumPag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumPag.setText("Numero de paginas");

        lblTitulo.setEditable(false);
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("Titulo del libro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(infoAutor)
                        .addGap(151, 151, 151))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoEditorial)
                            .addComponent(infoNumPag)
                            .addComponent(infoISBN)
                            .addComponent(infoAnhoPub)
                            .addComponent(infoIdioma)
                            .addComponent(infoEdicion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAnhoPub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblISBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumPag, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAutores))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoEditorial)
                            .addComponent(lblEditorial))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoEdicion)
                            .addComponent(lblEdicion))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoIdioma)
                            .addComponent(lblIdioma))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoAnhoPub)
                            .addComponent(lblAnhoPub))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoISBN)
                            .addComponent(lblISBN))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoNumPag)
                            .addComponent(lblNumPag)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(imgLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrestar)
                .addGap(18, 18, 18))
        );

        infoAutor.getAccessibleContext().setAccessibleName("txtAutor");
        infoIdioma.getAccessibleContext().setAccessibleName("txtIdioma");
        infoAnhoPub.getAccessibleContext().setAccessibleName("txtAnho");
        infoISBN.getAccessibleContext().setAccessibleName("txtIdentificador");
        btnPrestar.getAccessibleContext().setAccessibleName("btnReservar");
        imgLibro.getAccessibleContext().setAccessibleName("imgPortada");
        infoEditorial.getAccessibleContext().setAccessibleName("txtEditorial");
        infoEdicion.getAccessibleContext().setAccessibleName("txtEdicion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        String mensaje = "Se va a agregar un nuevo ejemplar de '" + libro.getTitulo() + "'. Continuar?";
        int ans = JOptionPane.showConfirmDialog(this, mensaje, "Nuevo ejemplar",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        switch(ans) {
            case JOptionPane.YES_OPTION:
                System.out.println("Se esta creando un ejemplar");
                EjemplarLibroDB eldb = new EjemplarLibroDB();
                Session session = Session.getSession();
                eldb.crearEjemplar(EstadoEjemplar.DISPONIBLE, libro, session.getBiblioteca(), 
                        session.getPiso());
                break;
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_btnPrestarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrestar;
    private javax.swing.JLabel imgLibro;
    private javax.swing.JLabel infoAnhoPub;
    private javax.swing.JLabel infoAutor;
    private javax.swing.JLabel infoEdicion;
    private javax.swing.JLabel infoEditorial;
    private javax.swing.JLabel infoISBN;
    private javax.swing.JLabel infoIdioma;
    private javax.swing.JLabel infoNumPag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAnhoPub;
    private javax.swing.JLabel lblAutores;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblNumPag;
    private javax.swing.JTextField lblTitulo;
    private javax.swing.JTable tablaEjemplares;
    // End of variables declaration//GEN-END:variables
}
