/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Search;

import Modelo.Autor;
import Modelo.Biblioteca;
import Modelo.Libro;
import Modelo.Piso;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author franco
 */
public class ResultadoLibro extends javax.swing.JPanel {

    private static final int LIMITE_VENTANAS = 3;
    
    private InformacionLibro editorLibro = null;
    //Lazy initialization
    private static Map<Libro, InformacionLibro> infoLibros = new HashMap<>();
    private final Libro libro;
    private static final Color COLOR_MOUSE_IN = new Color(0x937557),
            COLOR_MOUSE_OUT = new Color(0x999f99),
            BACKGROUND_COLOR = new Color(0x999f99),
            COLOR_MOUSE_PRESSING = new Color(0x575799);
    
    private boolean isPressing = false;
    private boolean isMouseIn = false;
    private final Thread imageLoadingThread;
    
    /**
     * Creates new form ResultadoLibro
     * @param libro
     */
    public ResultadoLibro(Libro libro) {
        
        initComponents();
        
        this.libro = libro;
        tituloLibro.setText(libro.getTitulo());
        String info = Autor.format(libro.getAutores());
        if(libro.getEdicion()>=1) info += ", " + libro.getEdicionString();
        info += ", " + libro.getAnhoPublicacion();
        infoLibro.setText(info);
        cantDisponible.setText(libro.getDisponibles()+"");
        cantReservada.setText(libro.getReservados()+"");
        imageLoadingThread = new Thread(new Runnable() {
            @Override
            public void run() {
                ImageIcon icon = libro.getPortada();
                if(icon!=null) {
                    imagenLibro.setIcon(icon);
                    imagenLibro.setText("");
                } else imagenLibro.setText("<html><body>sin<br>imagen</body></html>");
                System.out.println(infoLibro.getText());
            }
        });
        imageLoadingThread.start();
        
        pnlContenedor.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pnlContenedor.setBackground(COLOR_MOUSE_OUT);
        setBackground(BACKGROUND_COLOR);
    }
    
    public void kill() {
        imageLoadingThread.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        cantDisponible = new javax.swing.JLabel();
        imagenLibro = new javax.swing.JLabel();
        lblExistencias01 = new javax.swing.JLabel();
        cantReservada = new javax.swing.JLabel();
        tituloLibro = new javax.swing.JLabel();
        infoLibro = new javax.swing.JLabel();
        lblExistencias2 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(32767, 127));
        setMinimumSize(new java.awt.Dimension(705, 127));
        setPreferredSize(new java.awt.Dimension(705, 127));

        pnlContenedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlContenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlContenedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlContenedorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlContenedorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlContenedorMouseReleased(evt);
            }
        });

        cantDisponible.setText("###");

        imagenLibro.setText("imagen...");

        lblExistencias01.setText("Disponibles:");

        cantReservada.setText("###");

        tituloLibro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloLibro.setText("Titulo Libro");

        infoLibro.setText("Nombre del Autor, Numero de Edicion, Año de Publicacion");
        infoLibro.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblExistencias2.setText("Reservados:");

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addComponent(infoLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenedorLayout.createSequentialGroup()
                                .addComponent(lblExistencias2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantReservada))
                            .addGroup(pnlContenedorLayout.createSequentialGroup()
                                .addComponent(lblExistencias01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantDisponible))))
                    .addComponent(tituloLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedorLayout.createSequentialGroup()
                        .addComponent(tituloLibro)
                        .addGap(18, 18, 18)
                        .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlContenedorLayout.createSequentialGroup()
                                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblExistencias01)
                                    .addComponent(cantDisponible))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblExistencias2)
                                    .addComponent(cantReservada)))
                            .addComponent(infoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagenLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlContenedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlContenedorMouseEntered
        // TODO add your handling code here:
        isMouseIn = true;
        if(isPressing)
            pnlContenedor.setBackground(COLOR_MOUSE_PRESSING);
        else pnlContenedor.setBackground(COLOR_MOUSE_IN);
    }//GEN-LAST:event_pnlContenedorMouseEntered

    private void pnlContenedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlContenedorMouseExited
        // TODO add your handling code here:
        isMouseIn = false;
        if(isPressing)
            pnlContenedor.setBackground(COLOR_MOUSE_IN);
        else pnlContenedor.setBackground(COLOR_MOUSE_OUT);
    }//GEN-LAST:event_pnlContenedorMouseExited

    private void pnlContenedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlContenedorMousePressed
        // TODO add your handling code here:
        isPressing = true;
        pnlContenedor.setBackground(COLOR_MOUSE_PRESSING);
    }//GEN-LAST:event_pnlContenedorMousePressed

    private void pnlContenedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlContenedorMouseReleased
        // TODO add your handling code here:
        isPressing = false;
        if(isMouseIn) {
            pnlContenedor.setBackground(COLOR_MOUSE_IN);
            
            if(infoLibros.containsKey(libro)) {
                editorLibro = infoLibros.get(libro);
                editorLibro.setVisible(true);
                return;
            }

            if(infoLibros.size()>=LIMITE_VENTANAS) {
                int ans = JOptionPane.showConfirmDialog(this, "Ya tiene " + infoLibros.size() + " ventanas abiertas.\n¿Quiere abrir otra?", 
                        "Warning", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                if(ans==JOptionPane.CANCEL_OPTION || ans==JOptionPane.NO_OPTION) {
                    return;
                }
            }

            editorLibro = new InformacionLibro(libro);
            editorLibro.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    infoLibros.remove(libro);
                }
            });
            editorLibro.setVisible(true);
            infoLibros.put(libro, editorLibro);
        } else pnlContenedor.setBackground(COLOR_MOUSE_OUT);
    }//GEN-LAST:event_pnlContenedorMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantDisponible;
    private javax.swing.JLabel cantReservada;
    private javax.swing.JLabel imagenLibro;
    private javax.swing.JLabel infoLibro;
    private javax.swing.JLabel lblExistencias01;
    private javax.swing.JLabel lblExistencias2;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JLabel tituloLibro;
    // End of variables declaration//GEN-END:variables
}
