/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Search;

import DataAccess.SolicitudDB;
import Modelo.CorreoElectronico;
import Modelo.EnviarEmail;
import Modelo.Solicitud;
import Vista.Util;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class Solicitudes extends javax.swing.JInternalFrame {

    private static final String TMPL_STATS = "{0} solicitudes pendientes / {1} solicitudes revisadas";
    private static final String TMPL_TITLE = "Solicitud #{0}";
    private static final String TMPL_EMPTY_TITLE = "Solicitud #----------";
    private static final String TMPL_EMAIL = "Respuesta : ({0})";
    private static final String TMPL_EMPTY_EMAIL = "Respuesta :";
    private static final String TMPL_SUBJECT = "Respuesta a solicitud #{0}";
    private static final String TMPL_EMPTY_SUBJECT = "Respuesta a solicitud #----------";
    
    private ArrayList<Solicitud> solicitudes = new ArrayList<>();
    private int solicitudIndex = -1;
    
    private final SolicitudDB dbSolicitud = new SolicitudDB();
    
    
    public Solicitudes() {
        initComponents();
        solicitudIndex = 0;
        emptyAll();
        updateFrame();
    }
    
    //This updates all server data
    public void updateFrame() {
        Solicitud.SolicitudStat stats = dbSolicitud.getStats();
        labelEstadoSolicitudes.setText(
                Util.replaceVariables(TMPL_STATS, "" + stats.numPendientes,
                        "" + (stats.numTotales - stats.numPendientes)));
                
        //bFiltrar.setEnabled(false);
        //bFiltrar.setToolTipText(null);
        btnNext.setEnabled(false);
        btnPrev.setEnabled(false);
        
        solicitudes = dbSolicitud.getSolicitudes(false, 0, 1000);
        
        if(!solicitudes.isEmpty()) {
            //solicitudIndex = 0;
            if(solicitudIndex>=solicitudes.size()) {
                solicitudIndex = solicitudes.size()-1;
            } else if(solicitudIndex<0) solicitudIndex = 0;
            setCurrentRequest(solicitudes.get(solicitudIndex));
            updateArrowButtons();
        }
    }
    
    public void emptyAll() {
        labelTitle.setText(TMPL_EMPTY_TITLE);
        
        txtCodigoUsuario.setText("");
        txtNombreUsuario.setText("");
        txtISBN.setText("");
        txtFechaSolicitud.setText("");
        tfDescripcion.setText("");
        
        labelDestinatario.setText(TMPL_EMPTY_EMAIL);
        
        tfAsunto.setText(TMPL_EMPTY_SUBJECT);
        tfAsunto.setEnabled(false);
        tfCorreo.setText("");
        tfCorreo.setEnabled(false);
        bAnswer.setEnabled(false);
        //bSpam.setEnabled(false);
    }
    
    public void setCurrentRequest(Solicitud solicitud) {
        labelTitle.setText(Util.replaceVariables(TMPL_TITLE, 
                "" + solicitud.getIdSolicitud()));
        
        txtCodigoUsuario.setText(solicitud.getUsuario().getCodigo() + "");
        txtNombreUsuario.setText(solicitud.getUsuario().getNombreCompleto().toUpperCase());
        txtISBN.setText(solicitud.getIsbn());
        txtFechaSolicitud.setText(Util.format(solicitud.getFecha_solicitud()));
        tfDescripcion.setText(solicitud.getDescripcion());
        
        labelDestinatario.setText(Util.replaceVariables(TMPL_EMAIL, solicitud.getEmail()));
        
        tfAsunto.setText(Util.replaceVariables(TMPL_SUBJECT, solicitud.getIdSolicitud() + ""));
        tfAsunto.setEnabled(true);
        tfCorreo.setText("");
        tfCorreo.setEnabled(true);
        bAnswer.setEnabled(true);
        //bSpam.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        txtCodigoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtISBN = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        txtFechaSolicitud = new javax.swing.JTextField();
        labelEstadoSolicitudes = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfDescripcion = new javax.swing.JTextArea();
        labelDestinatario = new javax.swing.JLabel();
        tfAsunto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfCorreo = new javax.swing.JTextArea();
        bAnswer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Solicitudes");

        jPanel1.setMaximumSize(new java.awt.Dimension(528, 726));
        jPanel1.setMinimumSize(new java.awt.Dimension(528, 726));

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitle.setText("Solicitud #{0}");

        txtCodigoUsuario.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha de Solicitud : ");

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtISBN.setEditable(false);

        btnNext.setText(">");
        btnNext.setToolTipText("Siguiente");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Código de Usuario :");

        btnPrev.setText("<");
        btnPrev.setToolTipText("Anterior");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        txtFechaSolicitud.setEditable(false);

        labelEstadoSolicitudes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEstadoSolicitudes.setText("{0} solicitudes pendientes / {1} solicitudes");

        txtNombreUsuario.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Descripción :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nombre usuario :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ISBN : ");

        tfDescripcion.setEditable(false);
        tfDescripcion.setColumns(20);
        tfDescripcion.setRows(5);
        jScrollPane2.setViewportView(tfDescripcion);

        labelDestinatario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDestinatario.setText("Respuesta : ({0})");

        tfAsunto.setText("Respuesta a solicitud #{0}");

        tfCorreo.setColumns(20);
        tfCorreo.setRows(5);
        jScrollPane3.setViewportView(tfCorreo);

        bAnswer.setText("Responder");
        bAnswer.setEnabled(false);
        bAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreUsuario)
                            .addComponent(txtCodigoUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBN)
                            .addComponent(txtFechaSolicitud))))
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addComponent(labelEstadoSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAsunto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext)))
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelEstadoSolicitudes)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrev)
                        .addComponent(btnNext)
                        .addComponent(jButton1))
                    .addComponent(labelTitle))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDestinatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnswerActionPerformed
        // TODO add your handling code here:
        CorreoElectronico correo = new CorreoElectronico();
        correo.setAsunto(tfAsunto.getText());
        correo.setMensaje(tfCorreo.getText());
        correo.setDestino(solicitudes.get(solicitudIndex).getEmail());
        EnviarEmail sender = new EnviarEmail();
        sender.enviarCorreo(correo);
        solicitudes.get(solicitudIndex).setRevisada(true);
        //LLamar Base de Datos
        dbSolicitud.revisar_solicitud(solicitudes.get(solicitudIndex).getIdSolicitud());
        bAnswer.setEnabled(false);
        updateFrame();
    }//GEN-LAST:event_bAnswerActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        if(solicitudIndex<=0) {
            btnPrev.setEnabled(false);
            return;
        }
        solicitudIndex --;
        setCurrentRequest(solicitudes.get(solicitudIndex));
        btnNext.setEnabled(true);
        updateArrowButtons();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if(solicitudIndex+1 >= solicitudes.size()) {
            btnNext.setEnabled(false);
            return;
        }
        solicitudIndex ++;
        setCurrentRequest(solicitudes.get(solicitudIndex));
        btnPrev.setEnabled(true);
        updateArrowButtons();
    }//GEN-LAST:event_btnNextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateArrowButtons() {
        btnNext.setEnabled(solicitudIndex+1 < solicitudes.size());
        btnPrev.setEnabled(solicitudIndex > 0);
    }
       
    
    
    public void cleanTextField(){
        txtCodigoUsuario.setText("");
        txtFechaSolicitud.setText("");
        txtISBN.setText("");
        tfDescripcion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnswer;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDestinatario;
    private javax.swing.JLabel labelEstadoSolicitudes;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField tfAsunto;
    private javax.swing.JTextArea tfCorreo;
    private javax.swing.JTextArea tfDescripcion;
    private javax.swing.JTextField txtCodigoUsuario;
    private javax.swing.JTextField txtFechaSolicitud;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
