/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Startup;

import DataAccess.BibliotecarioDB;
import DataAccess.PrivilegioDB;
import DataAccess.Session;
import DataAccess.UsuarioDB;
import Modelo.Bibliotecario;
import Modelo.Privilegio;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class AdminPanel extends javax.swing.JFrame {

    private final Usuario usuario;
    
    public AdminPanel(Usuario usuario) {
        if(!usuario.isEsBibliotecario()) {
            JOptionPane.showMessageDialog(this, "No cuenta con los privilegios de administrador", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        Bibliotecario bibliotecario = BibliotecarioDB.getBibliotecario(usuario.getCodigo());
        Session session = new Session(usuario.getCodigo(), bibliotecario.getBiblioteca().getID(), bibliotecario.getPiso().getId());
        PrivilegioDB pdb = new PrivilegioDB();
        for(Privilegio p: pdb.getPrivilegios(bibliotecario))
            session.addPrivilegio(p);
        Session.setGlobalSession(session);
        //JOptionPane.showMessageDialog(this, "Ya ha iniciado sesion antes, cierre su otra sesion.", "Error", JOptionPane.ERROR_MESSAGE);
        //System.exit(0);
        this.usuario = usuario;
        initComponents();
        gestionbibliotecarios.GestionBibliotecas.centerWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        libraryButton1 = new javax.swing.JButton();
        libraryButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        labelWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccion de sesion");
        setResizable(false);

        jLabel5.setText("Atención a usuarios");

        libraryButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/book-stack.png"))); // NOI18N
        libraryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryButton1ActionPerformed(evt);
            }
        });

        libraryButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/library.png"))); // NOI18N
        libraryButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Gestión de bibliotecas");

        labelWelcome.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelWelcome.setText("Hola" + " " + usuario.getNombre() + "!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(libraryButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(libraryButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libraryButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libraryButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libraryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new UserServicePanel(BibliotecarioDB.getBibliotecario(usuario.getCodigo())).setVisible(true);
    }//GEN-LAST:event_libraryButton1ActionPerformed

    private void libraryButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new AdministrationPanel(BibliotecarioDB.getBibliotecario(usuario.getCodigo())).setVisible(true);
    }//GEN-LAST:event_libraryButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel(UsuarioDB.getUsuario(3)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JButton libraryButton1;
    private javax.swing.JButton libraryButton3;
    // End of variables declaration//GEN-END:variables
}
