/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Startup;

import DataAccess.BibliotecarioDB;
import DataAccess.EjemplarLibroDB;
import DataAccess.Session;
import Modelo.Biblioteca;
import Modelo.Bibliotecario;
import Modelo.EjemplarLibro;
import Vista.Pattern.DesktopTool;
import Vista.Pattern.DesktopToolListener;
import Vista.Pattern.FacadeDesktop;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public final class AdministrationPanel extends javax.swing.JFrame implements DesktopToolListener {

    private final Bibliotecario bibliotecario;
    private final Biblioteca biblioteca;
    
    private FacadeDesktop facadeDesktop;
    
    //Facade with lazy initialization
    private Map<String, JInternalFrame> tools = new HashMap<>();
    
    /**
     * Creates new form UserServicePanel
     * @param bibliotecario
     */
    public AdministrationPanel(final Bibliotecario bibliotecario) {
        this.bibliotecario = bibliotecario;
        biblioteca = bibliotecario.getBiblioteca();
        
        initComponents();
        setExtendedState( getExtendedState()|JFrame.MAXIMIZED_BOTH);
        setNombreBiblioteca(biblioteca.getNombre() + " : " + bibliotecario.getPiso());
        
        facadeDesktop = new FacadeDesktop(adminDesktop);
        facadeDesktop.addDesktopToolListener(this);
    }

    public void setNombreBiblioteca(String nombreBiblio) {
        if(nombreBiblio.length()>50) {
            String [] partes = nombreBiblio.split(" ");
            String lineaSup = new String();
            String lineaInf = new String();
            int len1 = nombreBiblio.length()/2;
            
            int i = 0;
            for(int l=0;l<len1 && i<partes.length; i++, l+=partes[i].length()+1)
                lineaSup += partes[i] + " ";
            for(;i<partes.length;i++) lineaInf += partes[i] + " ";
            System.out.println(lineaSup);
            System.out.println(lineaInf);
            labelNombreBiblioteca.setText("<html><body>" + lineaSup + "<br>" + lineaInf + "</body></html>");
        } else labelNombreBiblioteca.setText("<html><body>" + nombreBiblio + "</body></html>");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        botonBuscadorLibros = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        solicitud = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        botonReportes = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        botonAdminBibliotecas = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 32767));
        labelNombreBiblioteca = new javax.swing.JLabel();
        adminDesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atención a usuarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        botonBuscadorLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        botonBuscadorLibros.setText("Buscador de libros");
        botonBuscadorLibros.setFocusable(false);
        botonBuscadorLibros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBuscadorLibros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonBuscadorLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscadorLibrosActionPerformed(evt);
            }
        });
        jToolBar1.add(botonBuscadorLibros);
        jToolBar1.add(jSeparator1);

        solicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/message-icon.png"))); // NOI18N
        solicitud.setText("Solicitudes");
        solicitud.setFocusable(false);
        solicitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solicitud.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        solicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudActionPerformed(evt);
            }
        });
        jToolBar1.add(solicitud);
        jToolBar1.add(jSeparator4);

        botonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report-icon.png"))); // NOI18N
        botonReportes.setText("Reportes");
        botonReportes.setFocusable(false);
        botonReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportesActionPerformed(evt);
            }
        });
        jToolBar1.add(botonReportes);
        jToolBar1.add(jSeparator6);

        botonAdminBibliotecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minitool.png"))); // NOI18N
        botonAdminBibliotecas.setText("Bibliotecas");
        botonAdminBibliotecas.setFocusable(false);
        botonAdminBibliotecas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAdminBibliotecas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAdminBibliotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminBibliotecasActionPerformed(evt);
            }
        });
        jToolBar1.add(botonAdminBibliotecas);
        jToolBar1.add(filler1);

        labelNombreBiblioteca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNombreBiblioteca.setText("<html><body>Nombre<br>Biblioteca</body></html>");
        jToolBar1.add(labelNombreBiblioteca);

        javax.swing.GroupLayout adminDesktopLayout = new javax.swing.GroupLayout(adminDesktop);
        adminDesktop.setLayout(adminDesktopLayout);
        adminDesktopLayout.setHorizontalGroup(
            adminDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        adminDesktopLayout.setVerticalGroup(
            adminDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
            .addComponent(adminDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminDesktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscadorLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscadorLibrosActionPerformed
        // TODO add your handling code here:
        if(facadeDesktop.addTool(DesktopTool.BUSCADOR_LIBROS)) {
            botonBuscadorLibros.setEnabled(false);
        } else {
            botonBuscadorLibros.setEnabled(true);
        }
    }//GEN-LAST:event_botonBuscadorLibrosActionPerformed

    private void solicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudActionPerformed
        // TODO add your handling code here:
        if(facadeDesktop.addTool(DesktopTool.SOLICITUDES)) {
            solicitud.setEnabled(false);
        } else {
            solicitud.setEnabled(true);
        }
    }//GEN-LAST:event_solicitudActionPerformed

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
        // TODO add your handling code here:
        if(facadeDesktop.addTool(DesktopTool.REPORTES)) {
            botonReportes.setEnabled(false);
        } else {
            botonReportes.setEnabled(true);
        }
    }//GEN-LAST:event_botonReportesActionPerformed

    private void botonAdminBibliotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminBibliotecasActionPerformed
        // TODO add your handling code here:
        if(facadeDesktop.addTool(DesktopTool.GESTION_BIBLIOTECA))
            botonAdminBibliotecas.setEnabled(false);
        else botonAdminBibliotecas.setEnabled(true);
    }//GEN-LAST:event_botonAdminBibliotecasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Session.getSession().clearLocks();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrationPanel(BibliotecarioDB.getBibliotecario(3)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane adminDesktop;
    private javax.swing.JButton botonAdminBibliotecas;
    private javax.swing.JButton botonBuscadorLibros;
    private javax.swing.JButton botonReportes;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelNombreBiblioteca;
    private javax.swing.JButton solicitud;
    // End of variables declaration//GEN-END:variables

    @Override
    public void DesktopToolClosing(DesktopTool tool) {
        switch(tool) {
            case BUSCADOR_LIBROS:
                botonBuscadorLibros.setEnabled(true);
                break;
            case REPORTES:
                botonReportes.setEnabled(true);
                break;
            case SOLICITUDES:
                solicitud.setEnabled(true);
                break;
            case GESTION_BIBLIOTECA:
                botonAdminBibliotecas.setEnabled(true);
                break;
        }
    }
}
