/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Gestion;

import DataAccess.PrestamoDB;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class DevolverPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form DevolverPrestamo
     */
    public DevolverPrestamo() {
        initComponents();
        ejemplarID.setEnabled(false);
        //usuarioID.setEnabled(false);
        updateBoton.setEnabled(false);
        gestionbibliotecarios.GestionBibliotecas.centerWindow(this);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonNuevo = new javax.swing.JButton();
        updateBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ejemplarID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        updateBoton.setText("Actualizar Préstamo");
        updateBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("Ejemplar");

        jLabel4.setText("Inserte un número de ejemplar");

        ejemplarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplarIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(botonNuevo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ejemplarID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBoton))))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ejemplarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(updateBoton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void updateBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBotonActionPerformed
        
        int idEjemplar; 
        
        
//        String prestamo = prestamoID.getText();
//        String usuario = usuarioID.getText();
        String ejemplar = ejemplarID.getText();
        
        if(ejemplar.isEmpty()/*prestamo.isEmpty() && usuario.isEmpty()*/){
            JOptionPane.showMessageDialog(this,"Ingrese un número de ejemplar!", "Advertencia", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Codigo para desechar
//        else if(ejemplar.isEmpty()){
//            JOptionPane.showMessageDialog(this,"Inserte un número de prestamo", "Advertencia", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        else if(usuario.isEmpty()){
//            JOptionPane.showMessageDialog(this,"Inserte un número de usuario", "Advertencia", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
        
        boolean p = isNumeric(ejemplar);
        //boolean u= isNumeric(usuario);
        if(p == false){
            JOptionPane.showMessageDialog(this,"El campo debe ser numérico", "Advertencia", JOptionPane.ERROR_MESSAGE);
            return;
        }
//        if(p == false || u == false){
//            JOptionPane.showMessageDialog(this,"Los campos deben ser numéricos", "Advertencia", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
        idEjemplar = Integer.parseInt(ejemplar);
        //idUsuario = Integer.parseInt(usuario);
        if(PrestamoDB.existePrestamo(idEjemplar) != 0){
             int devolver_prestamo = PrestamoDB.updatePrestamo(idEjemplar);
            if(devolver_prestamo != 0){
                JOptionPane.showMessageDialog(this,"Devolución Exitosa", "Detalle Préstamo", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(this,"Error al actualizar el préstamo", "Detalle Préstamo", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }else{
            JOptionPane.showMessageDialog(this,"El préstamo no existe.Inténtelo nuevamente", "Detalle Préstamo", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        ejemplarID.setText("");
        //usuarioID.setText("");
        ejemplarID.setEnabled(false);
        //usuarioID.setEnabled(false);
        updateBoton.setEnabled(false);
        botonNuevo.setEnabled(true);
      
    }//GEN-LAST:event_updateBotonActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
        ejemplarID.setEnabled(true);
        //usuarioID.setEnabled(true);
        updateBoton.setEnabled(true);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void ejemplarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejemplarIDActionPerformed

    
    private static boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevolverPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevolverPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevolverPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevolverPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevolverPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonNuevo;
    private javax.swing.JTextField ejemplarID;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton updateBoton;
    // End of variables declaration//GEN-END:variables
}
