/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Gestion;

import DataAccess.PrestamoDB;
import DataAccess.ReservaDB;
import Modelo.Reserva;
import Modelo.UsuarioBiblioteca;
import Vista.Pattern.DesktopTool;
import Vista.Pattern.FacadeDesktop;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franc
 */
public class GestionReservas extends javax.swing.JInternalFrame {
    
    private static final String[] COLUMNS = { "IdReserva", "IdEjemplar", "Titulo", "Marcar" };
    
    private final UsuarioBiblioteca usuario;
    private ArrayList<Reserva> reservas;
    
    private final FacadeDesktop parent;
    /**
     * Creates new form GestionReservas
     * @param usuario
     */
    public GestionReservas(UsuarioBiblioteca usuario, FacadeDesktop parent) {
        this.usuario = usuario;
        this.parent = parent;
        
        initComponents();
        labelNombre.setText(usuario.getNombreCompleto().toUpperCase());
        updateReservas();
    }
    
    public void updateReservas() {
        ReservaDB reservadb = new ReservaDB();
        reservas = reservadb.getAllReservas(usuario);
        
        Object [][] data = new Object[reservas.size()][5];
        for(int i=0;i<reservas.size();i++) {
            Reserva reserva = reservas.get(i);
            
            data[i][0] = "" + reserva.getIdReserva();
            data[i][1] = "" + reserva.getLibro().getId();
            data[i][2] = "" + reserva.getLibro().getTitulo();
            data[i][3] = (Boolean)false;
        }
        
        tablaReservas.setModel(new DefaultTableModel(data, COLUMNS){
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return String.class;
                    case 1:
                        return String.class;
                    case 2:
                        return String.class;
                    case 3:
                        return Boolean.class;
                }
                return String.class;
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return column==3;
            }
        });
        tablaReservas.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReservas = new javax.swing.JTable();
        labelNombre = new javax.swing.JLabel();
        btnGenerarPrestamo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reserva");

        tablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReservas);

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelNombre.setText("NOMBRE DEL QUE RESERVO");

        btnGenerarPrestamo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGenerarPrestamo.setText("Generar préstamo");
        btnGenerarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPrestamoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnGenerarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGenerarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPrestamoActionPerformed
        // TODO add your handling code here:
        ArrayList<Reserva> subset = new ArrayList<>();
        int len = tablaReservas.getRowCount();
        for(int i=0;i<len;i++) {
            Boolean b = (Boolean) tablaReservas.getValueAt(i, 3);
            if(b) subset.add(reservas.get(i));
        }
        
        int tot = PrestamoDB.cuentaPrestamosUsuario(usuario.getCodigo());
        int max = usuario.getMaxReserva();
        
        if((tot + subset.size()) > max) {
            JOptionPane.showMessageDialog(this, "El usuario ya tiene " + tot + " de " + max + "libros prestados",
                    "No se puede prestar", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        GenerarPrestamo prestamo = new GenerarPrestamo(usuario);
        ReservaDB rdb = new ReservaDB();
        rdb.removeAllReservas(subset);
        prestamo.btnGenerarPrestamo.doClick();
        
        for(Reserva r: subset) {
            prestamo.addBook(r.getLibro());
        }
    }//GEN-LAST:event_btnGenerarPrestamoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarPrestamo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTable tablaReservas;
    // End of variables declaration//GEN-END:variables
}
