/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Gestion;

import DataAccess.UsuarioBibliotecaDB;
import DataAccess.UsuarioDB;
import Modelo.Usuario;
import Modelo.UsuarioBiblioteca;
import Vista.DataModel.NonEditableTableModel;
import Vista.Startup.AdminMain;
import Vista.Listener.ChangeStringListener;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author alulab14
 */
public class GestionUsuarios extends javax.swing.JFrame implements ChangeStringListener {

    /**
     * Creates new form GestionBibliotecarios
     */
    private static final String [] TABLE_COLUMNS = {"ID", "Nombre", "Apellido Paterno","Apellido Materno","Tipo","Estado"};
    
    //private ArrayList<Usuario> bibliotecasDisponibles = new ArrayList<>();
    private ArrayList<UsuarioBiblioteca> usuarios = new ArrayList<>();
    
    private UsuarioBiblioteca seleccionado = null;
    
    private UsuarioBiblioteca objBiblioteca = null;
    private UsuarioBibliotecaDB dbUsuario = new  UsuarioBibliotecaDB();
    public GestionUsuarios() {
        initComponents();
        
        gestionbibliotecarios.GestionBibliotecas.centerWindow(this);
        updateDataUsuarios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTable = new javax.swing.JTable();
        buscarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Usuarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        usuariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Tipo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(usuariosTable);

        buscarUsuario.setText("Buscar Usuario");
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarUsuario)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateDataUsuarios(){
        String estado = null;
         usuarios = dbUsuario.getUsuarios(0, 100);
        String [][] data = new String[usuarios.size()][6];
        for(int i=0;i<usuarios.size();i++) {
            data[i][0] = usuarios.get(i).getCodigo()+"";
            data[i][1] = usuarios.get(i).getNombre()+ "";
            data[i][2] = usuarios.get(i).getApPaterno() + "";
            data[i][3] = usuarios.get(i).getApMaterno()+ "";
            
            data[i][4] = usuarios.get(i).getTipo().getTipo()+ "";
            if(usuarios.get(i).isActivo()) estado = "Habilitado"; else estado = "Suspendido"; 
            data[i][5] = estado;
        }
        usuariosTable.setModel(new NonEditableTableModel(data, TABLE_COLUMNS));
    }            
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new AdminMain().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        // TODO add your handling code here:
        RegistroUsuario frame = new RegistroUsuario();
        frame.setVisible(true);
        frame.setDefaultCloseOperation(RegistroBibliotecario.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_buscarUsuarioActionPerformed

    
//      public void cleanCampos(){
//        idLabel.setText("####");
//        nameField.setText("");
//        apellidoPat.setText("");
//        apellidoMat.setText("");
//        emailField.setText("");
//        
//        areaBox.setEnabled(false);
//       
//    }
//      private void nuevoBibliotecario() {
//        // TODO add your handling code here:
//        codigoField.setEnabled(true);
//        nameField.setEnabled(true);
//        apellidoPat.setEnabled(true);
//        apellidoMat.setEnabled(true);
//        emailField.setEnabled(true);
//        selectedBiblioteca.setEnabled(true);
//        areaBox.setEnabled(true);
//        turnoBox.setEnabled(true);
//        
//        nuevoButton.setEnabled(false);
//        cancelButton.setEnabled(true);
//        addButton.setEnabled(true);
//    }
//    
//    private void cancelarBibliotecario() {
//         // TODO add your handling code here:
//        codigoField.setEnabled(true);
//        nameField.setEnabled(false);
//        apellidoPat.setEnabled(false);
//        apellidoMat.setEnabled(false);
//        emailField.setEnabled(false);
//        selectedBiblioteca.setEnabled(false);
//        areaBox.setEnabled(false);
//        turnoBox.setEnabled(false);
//        
//        addButton.setEnabled(false);
//        updateButton.setEnabled(false);
//        //searchButton.setEnabled(true);
//        nuevoButton.setEnabled(true);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable usuariosTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambiarTexto(int index, String nuevo) {
    }
}
