/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Gestion;

import Reporte.GenerarReporte;

/**
 *
 * @author franc
 */
public class GestionReporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionReporte
     */
    public GestionReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        librosDisp = new javax.swing.JButton();
        librosPrest = new javax.swing.JButton();
        librosMant = new javax.swing.JButton();
        librosNoRec = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestion Resportes");

        librosDisp.setText("Ver libros disponibles");
        librosDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosDispActionPerformed(evt);
            }
        });

        librosPrest.setText("Ver libros prestados");
        librosPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosPrestActionPerformed(evt);
            }
        });

        librosMant.setText("Ver libros en mantenimiento");
        librosMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosMantActionPerformed(evt);
            }
        });

        librosNoRec.setText("Ver libros no recuperados");
        librosNoRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosNoRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(librosDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(librosPrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(librosMant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(librosNoRec, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(librosDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(librosPrest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(librosMant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(librosNoRec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librosDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosDispActionPerformed
        // TODO add your handling code here:
        GenerarReporte g = new GenerarReporte();
        g.reporteLibrosDisponibles();
    }//GEN-LAST:event_librosDispActionPerformed

    private void librosPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosPrestActionPerformed
        // TODO add your handling code here:
        GenerarReporte g = new GenerarReporte();
        g.reporteLibrosPrestados();
    }//GEN-LAST:event_librosPrestActionPerformed

    private void librosMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosMantActionPerformed
        // TODO add your handling code here:
        GenerarReporte g = new GenerarReporte();
        g.reporteLibrosEnMantenimiento();
    }//GEN-LAST:event_librosMantActionPerformed

    private void librosNoRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosNoRecActionPerformed
        // TODO add your handling code here:
        GenerarReporte g = new GenerarReporte();
        g.reporteLibrosNoRecuperados();
    }//GEN-LAST:event_librosNoRecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton librosDisp;
    private javax.swing.JButton librosMant;
    private javax.swing.JButton librosNoRec;
    private javax.swing.JButton librosPrest;
    // End of variables declaration//GEN-END:variables
}
