/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Gestion;

import DataAccess.UsuarioBibliotecaDB;
import Modelo.UsuarioBiblioteca;
import Vista.DataModel.NonEditableTableModel;
import Vista.Pattern.DesktopTool;
import Vista.Pattern.FacadeDesktop;
import java.util.ArrayList;
import javax.swing.JDesktopPane;

/**
 *
 * @author franc
 */
public final class GestionUsuariosIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionUsuariosIF
     */
    private static final String [] TABLE_COLUMNS = {"ID", "Nombre", "Apellido Paterno","Apellido Materno","Tipo","Estado"};
    
    //private ArrayList<Usuario> bibliotecasDisponibles = new ArrayList<>();
    private ArrayList<UsuarioBiblioteca> usuarios = new ArrayList<>();
    
    private UsuarioBiblioteca seleccionado = null;
    
    private UsuarioBiblioteca objBiblioteca = null;
    private UsuarioBibliotecaDB dbUsuario = new  UsuarioBibliotecaDB();
    
    private final FacadeDesktop parent;
    
    public GestionUsuariosIF(final FacadeDesktop parent) {
        this.parent = parent;
        initComponents();
        
        updateDataUsuarios();
    }

    public void updateDataUsuarios(){
        String estado = null;
         usuarios = dbUsuario.getUsuarios(0, 100);
        String [][] data = new String[usuarios.size()][6];
        for(int i=0;i<usuarios.size();i++) {
            data[i][0] = usuarios.get(i).getCodigo()+"";
            data[i][1] = usuarios.get(i).getNombre()+ "";
            data[i][2] = usuarios.get(i).getApPaterno() + "";
            data[i][3] = usuarios.get(i).getApMaterno()+ "";
            
            data[i][4] = usuarios.get(i).getTipo().getTipo()+ "";
            if(usuarios.get(i).isHabilitado()) estado = "Habilitado"; else estado = "Suspendido"; 
            data[i][5] = estado;
        }
        usuariosTable.setModel(new NonEditableTableModel(data, TABLE_COLUMNS));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTable = new javax.swing.JTable();
        buscarUsuario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion usuarios");

        usuariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Tipo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(usuariosTable);

        buscarUsuario.setText("Buscar Usuario");
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarUsuario)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        // TODO add your handling code here:
        parent.addTool(DesktopTool.BUSCAR_USUARIO);
    }//GEN-LAST:event_buscarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable usuariosTable;
    // End of variables declaration//GEN-END:variables
}
